# This is a basic workflow to help you get started with Actions

name: Run XSeed Collection

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0

      # Installs the required newman and newman html reporter packages
      - name: Install newman and reporter package with global scope
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # Uploads report artifacts which can be downloaded post run is complete
      - name: Run XSeed Standard Lesson Plan Collection
        id: runCollection
        run: |
          newman run postman_collection/CreateAStandardLessonPlan.postman_collection.json -r "htmlextra,cli" --bail
          newman run postman_collection/CreateMultiBlockProjectLessonPlan.postman_collection.json -r "htmlextra,cli" --bail
          newman run postman_collection/ValidateAStandardProject.postman_collection.json -r "htmlextra,cli" --bail
        continue-on-error: true
    
      # Uploads report artifacts which can be downloaded post run is complete
      - name: Upload Reports
        uses: actions/upload-artifact@v2.2.4
        with:
          name: ResultsStandardLessonPlan
          path: newman
       
     # it checks if the collection run was failed and in turn marks the build as failed
      - name: Check if tests were failed   
        if: steps.runCollection.outcome != 'success'
        run: |
          echo "There were test failures"
          exit 1
